import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:firebase_core/firebase_core.dart';

import 'app.dart';
import 'providers/app_providers.dart';
import 'core/di/injection.dart';
import 'services/profile_local_datasource.dart';
import 'features/profiles/data/models/profile_model.dart';
import 'features/profiles/data/models/todo_model.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await Firebase.initializeApp();
  } catch (e) {
    debugPrint('Firebase initialization failed: $e. Falling back to stubs.');
  }

  // 1. Initialize Hive
  await Hive.initFlutter();

  // Register Hive adapters (generated by hive_generator)
  Hive.registerAdapter(ProfileModelAdapter());
  Hive.registerAdapter(TodoModelAdapter());

  // Open Hive boxes
  await ProfileLocalDatasource.openBoxes();

  // 2. Initialize dependency injection
  await configureDependencies();

  // 3. Run app
  runApp(
    MultiProvider(
      providers: AppProviders.providers,
      child: const WorkspaceEngineApp(),
    ),
  );
}
